# preload = ~/.config/skxxtz/backgrounds/bg1.jpg
preload = ~/Downloads/wallpaper.avif

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
# wallpaper = eDP-1,~/.config/skxxtz/backgrounds/bg1.jpg
wallpaper = eDP-1,~/Downloads/wallpaper.avif

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off


