monitor                         = eDP-1,preferred -vsync ,auto,1.5
monitor                         = HDMI-A-1,preffered,auto,2,mirror,eDP-1
monitor                         = *,preffered,auto,1.5

# REMOVE UPDATE INFORMATION
ecosystem:no_update_news        = true

# ENVIRONMENT VARIABLES
$terminal                       = kitty
$fileManager                    = $terminal ranger
$menu                           = echo "show" | nc -U /tmp/sherlock_daemon.socket 
$menu                           = sherlock

env                             = XCURSOR_SIZE,24
env                             = QT_QPA_PLATFORMTHEME,qt6ct 
env                             = GTK_THEME, WhiteSur-Dark

# SOURCE FILES
source                          = ~/.config/hypr/hyprland_startup.conf
source                          = ~/.config/hypr/hyprland_binds.conf
source                          = ~/.config/hypr/hyprland_devices.conf
source                          = ~/.config/hypr/hyprland_window_rules.conf


# STYLE
# https://wiki.hyprland.org/Configuring/Variables/ 
# https://wiki.hyprland.org/Configuring/Animations/ 
#
misc { 
    font_family                 = "Cantarell 12"
    force_default_wallpaper     = 0 
    disable_hyprland_logo       = true
}

decoration {
    rounding                    = 0
    blur {
        enabled                 = true
        size                    = 3
        passes                  = 1
    }
##    drop_shadow                 = yes
##    shadow_range                = 4
##    shadow_render_power         = 3
##    col.shadow                  = rgba(1a1a1aee)
}

general {
    gaps_in                     = 0
    gaps_out                    = 0
    border_size                 = 0

    col.active_border           = rgb(303030)
    col.inactive_border         = rgb(171717)

    layout                      = dwindle
    allow_tearing               = true

}

animations {
#   animation                   = NAME, ONOFF, SPEED, CURVE, [,STYLE]
    enabled                     = none
    bezier                      = myBezier, 0.05, 0.9, 0.1, 1
    animation                   = windows, 1, 2, myBezier
    animation                   = border, 1, 10, default
    animation                   = borderangle, 1, 8, default
    animation                   = fade, 1, 7, default
    animation                   = workspaces, 1, 6, default
}

dwindle {
    pseudotile                  = yes
    preserve_split              = yes
    force_split                 = 1 # 2 Makes new tiles appear on the right side
}
