# ~/.bashrc
[[ $- != *i* ]] && return

export PATH="$HOME/.pyenv/shims:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
alias ls='ls --color=auto'
alias lls='ls -a --color=auto'
alias grep='grep --color=auto'
export TERMINAL=kitty
PS1='[\u@\h \W]\$ '

